[package]
name = "evo-marker"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
bitcode = ["dep:bitcode"]

[dependencies]
bitcode = { version = "0.6.5", optional = true, default-features = false, features = [
  "derive",
] }
itertools = "0.14.0"
rand = { version = "0.9.0" }
