use std::{
    fmt,
    hash::{Hash, Hasher},
    marker::PhantomData,
};

use rand::Rng;

use crate::scheduler::update::ChannelRecomputeSink;

/// Model state and event semantics shared by a compile-time reaction-family set.
pub trait StaticFamilyModel: Sized {
    /// Mutable biological state advanced by reaction events.
    type State;

    /// Compact description of one fired reaction and its affected state.
    type Event;

    /// Compile-time family bundle used by this model.
    type Families;

    /// Build the initial simulation state.
    fn initial_state(&self) -> Self::State;

    /// Report every existing channel whose cached propensity changed after `event`.
    ///
    /// Newly appended suffix channels are initialized automatically. A reused local slot whose
    /// biological meaning changed must be reported with
    /// [`ChannelRecomputeSink::reinitialize_family`].
    fn refresh_after_event<U>(&self, state: &Self::State, event: &Self::Event, updates: &mut U)
    where
        U: ChannelRecomputeSink<Self::Families> + ?Sized;
}

/// One compile-time reaction family containing a dynamic number of concrete channels.
///
/// Local channel ids are dense scheduler slots within this family. Existing ids keep the same
/// biological meaning until the model explicitly reinitializes a reused slot. Families may append
/// channels or remove a suffix by changing [`channel_count`](Self::channel_count).
pub trait StaticReactionFamily<M: StaticFamilyModel> {
    /// Return the number of currently addressable concrete channels in this family.
    fn channel_count(&self, model: &M, state: &M::State) -> usize;

    /// Return one channel's current propensity.
    ///
    /// Schedulers cache this value until the model emits a matching dependency update.
    fn propensity(&self, model: &M, state: &M::State, local_channel: usize, time: f64) -> f64;

    /// Fire one concrete channel and return the resulting model event.
    fn fire<R: Rng + ?Sized>(
        &self,
        model: &M,
        state: &mut M::State,
        local_channel: usize,
        rng: &mut R,
    ) -> M::Event;
}

/// A reaction-family identifier branded by its compile-time family bundle.
///
/// Values are normally generated by [`reaction_families!`](crate::reaction_families), which gives
/// each family a stable named enum variant without exposing positional integers to model code.
pub struct FamilyId<F> {
    index: usize,
    family_set: PhantomData<fn() -> F>,
}

impl<F> FamilyId<F> {
    /// Return this family's zero-based position inside its family bundle.
    #[inline(always)]
    pub const fn index(self) -> usize {
        self.index
    }

    #[doc(hidden)]
    #[inline(always)]
    ///
    /// # Safety
    ///
    /// `index` must name a family in `F` and must use the same ordering as the family value.
    pub const unsafe fn __from_index_unchecked(index: usize) -> Self {
        Self {
            index,
            family_set: PhantomData,
        }
    }
}

impl<F> Clone for FamilyId<F> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<F> Copy for FamilyId<F> {}

impl<F> fmt::Debug for FamilyId<F> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("FamilyId")
            .field(&self.index)
            .finish()
    }
}

impl<F> PartialEq for FamilyId<F> {
    fn eq(&self, other: &Self) -> bool {
        self.index == other.index
    }
}

impl<F> Eq for FamilyId<F> {}

impl<F> Hash for FamilyId<F> {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.index.hash(state);
    }
}

/// End marker for a recursively composed static reaction-family list.
#[derive(Debug, Clone, Copy, Default)]
pub struct FamilyNil;

/// One family followed by the rest of a recursively composed static family list.
#[derive(Debug, Clone, Copy)]
pub struct FamilyCons<H, T> {
    pub(crate) head: H,
    pub(crate) tail: T,
}

/// Nominal wrapper that brands a static family list with a model-specific tag.
#[derive(Debug, Clone, Copy)]
pub struct FamilyBundle<Tag, L> {
    pub(crate) families: L,
    tag: PhantomData<fn() -> Tag>,
}

impl<Tag, L> FamilyBundle<Tag, L> {
    /// Brand an ordered family list for the corresponding `reaction_families!` declaration.
    #[doc(hidden)]
    #[inline(always)]
    pub const fn new(families: L) -> Self {
        Self {
            families,
            tag: PhantomData,
        }
    }
}

impl<H, T> FamilyCons<H, T> {
    /// Prepend `head` to `tail`.
    #[inline(always)]
    pub const fn new(head: H, tail: T) -> Self {
        Self { head, tail }
    }
}

mod sealed {
    pub trait FamilyReactionSet {}
}

impl sealed::FamilyReactionSet for FamilyNil {}

impl<H, T> sealed::FamilyReactionSet for FamilyCons<H, T> where T: sealed::FamilyReactionSet {}

impl<Tag, L> sealed::FamilyReactionSet for FamilyBundle<Tag, L> where L: sealed::FamilyReactionSet {}

/// Internal dispatch contract implemented by arbitrary-length static family lists.
#[doc(hidden)]
pub trait FamilyReactionSet<M: StaticFamilyModel>: sealed::FamilyReactionSet {
    const FAMILY_COUNT: usize;

    fn channel_count(&self, model: &M, state: &M::State, family: usize) -> Option<usize>;

    fn propensity(
        &self,
        model: &M,
        state: &M::State,
        family: usize,
        local_channel: usize,
        time: f64,
    ) -> Option<f64>;

    fn fire<R: Rng + ?Sized>(
        &self,
        model: &M,
        state: &mut M::State,
        family: usize,
        local_channel: usize,
        rng: &mut R,
    ) -> Option<M::Event>;
}

impl<M> FamilyReactionSet<M> for FamilyNil
where
    M: StaticFamilyModel,
{
    const FAMILY_COUNT: usize = 0;

    #[inline(always)]
    fn channel_count(&self, _model: &M, _state: &M::State, _family: usize) -> Option<usize> {
        None
    }

    #[inline(always)]
    fn propensity(
        &self,
        _model: &M,
        _state: &M::State,
        _family: usize,
        _local_channel: usize,
        _time: f64,
    ) -> Option<f64> {
        None
    }

    #[inline(always)]
    fn fire<R: Rng + ?Sized>(
        &self,
        _model: &M,
        _state: &mut M::State,
        _family: usize,
        _local_channel: usize,
        _rng: &mut R,
    ) -> Option<M::Event> {
        None
    }
}

impl<M, H, T> FamilyReactionSet<M> for FamilyCons<H, T>
where
    M: StaticFamilyModel,
    H: StaticReactionFamily<M>,
    T: FamilyReactionSet<M>,
{
    const FAMILY_COUNT: usize = 1 + T::FAMILY_COUNT;

    #[inline(always)]
    fn channel_count(&self, model: &M, state: &M::State, family: usize) -> Option<usize> {
        if family == 0 {
            Some(self.head.channel_count(model, state))
        } else {
            self.tail.channel_count(model, state, family - 1)
        }
    }

    #[inline(always)]
    fn propensity(
        &self,
        model: &M,
        state: &M::State,
        family: usize,
        local_channel: usize,
        time: f64,
    ) -> Option<f64> {
        if family == 0 {
            Some(self.head.propensity(model, state, local_channel, time))
        } else {
            self.tail
                .propensity(model, state, family - 1, local_channel, time)
        }
    }

    #[inline(always)]
    fn fire<R: Rng + ?Sized>(
        &self,
        model: &M,
        state: &mut M::State,
        family: usize,
        local_channel: usize,
        rng: &mut R,
    ) -> Option<M::Event> {
        if family == 0 {
            Some(self.head.fire(model, state, local_channel, rng))
        } else {
            self.tail.fire(model, state, family - 1, local_channel, rng)
        }
    }
}

impl<M, Tag, L> FamilyReactionSet<M> for FamilyBundle<Tag, L>
where
    M: StaticFamilyModel,
    L: FamilyReactionSet<M>,
{
    const FAMILY_COUNT: usize = L::FAMILY_COUNT;

    #[inline(always)]
    fn channel_count(&self, model: &M, state: &M::State, family: usize) -> Option<usize> {
        self.families.channel_count(model, state, family)
    }

    #[inline(always)]
    fn propensity(
        &self,
        model: &M,
        state: &M::State,
        family: usize,
        local_channel: usize,
        time: f64,
    ) -> Option<f64> {
        self.families
            .propensity(model, state, family, local_channel, time)
    }

    #[inline(always)]
    fn fire<R: Rng + ?Sized>(
        &self,
        model: &M,
        state: &mut M::State,
        family: usize,
        local_channel: usize,
        rng: &mut R,
    ) -> Option<M::Event> {
        self.families.fire(model, state, family, local_channel, rng)
    }
}

/// Construct an arbitrary-length, statically typed reaction-family list.
#[macro_export]
macro_rules! family_list {
    () => {
        $crate::scheduler::family::FamilyBundle::new(
            $crate::scheduler::family::FamilyNil
        )
    };
    ($head:expr $(, $tail:expr)* $(,)?) => {
        $crate::scheduler::family::FamilyBundle::new(
            $crate::family_list!(@list $head $(, $tail)*)
        )
    };
    (@list) => {
        $crate::scheduler::family::FamilyNil
    };
    (@list $head:expr $(, $tail:expr)*) => {
        $crate::scheduler::family::FamilyCons::new(
            $head,
            $crate::family_list!(@list $($tail),*)
        )
    };
}

/// Declare an arbitrary-length family-list type and its named, bundle-branded family ids.
///
/// The declared family types must appear in the same order when constructing the value with
/// [`family_list!`](crate::family_list).
#[macro_export]
macro_rules! reaction_families {
    (
        $(#[$set_meta:meta])*
        $set_vis:vis type $set:ident;
        $(#[$id_meta:meta])*
        $id_vis:vis enum $family_id:ident {
            $($variant:ident => $family:ty),+ $(,)?
        }
    ) => {
        $(#[$set_meta])*
        $set_vis type $set = $crate::scheduler::family::FamilyBundle<
            $family_id,
            $crate::reaction_families!(@list_type $($family),+)
        >;

        $(#[$id_meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[repr(usize)]
        $id_vis enum $family_id {
            $($variant),+
        }

        impl From<$family_id> for $crate::scheduler::family::FamilyId<$set> {
            fn from(family: $family_id) -> Self {
                // SAFETY: the macro emits the enum and family-list type from the same ordered list.
                unsafe { Self::__from_index_unchecked(family as usize) }
            }
        }
    };
    (@list_type $head:ty $(, $tail:ty)*) => {
        $crate::scheduler::family::FamilyCons<
            $head,
            $crate::reaction_families!(@list_type $($tail),*)
        >
    };
    (@list_type) => {
        $crate::scheduler::family::FamilyNil
    };
}
