use std::marker::PhantomData;

use crate::scheduler::family::FamilyId;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum FamilyUpdateKind {
    Recompute,
    Reinitialize,
}

/// One dependency update addressed by family and local scheduler slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[doc(hidden)]
pub struct FamilyChannelUpdate {
    pub(crate) family: usize,
    pub(crate) local_channel: usize,
    pub(crate) kind: FamilyUpdateKind,
}

/// Callback sink used by static-family models to report affected channels.
///
/// `recompute` addresses a channel in the family that fired. Cross-family methods accept a
/// bundle-branded [`FamilyId`], normally produced from the named enum generated by
/// [`reaction_families!`](crate::reaction_families).
pub trait ChannelRecomputeSink<F> {
    /// Recompute a channel in the family that fired while preserving an unaffected NRM clock.
    fn recompute(&mut self, local_channel: usize);

    /// Recompute a channel in a named family while preserving an unaffected NRM clock.
    fn recompute_family<I>(&mut self, family: I, local_channel: usize)
    where
        I: Into<FamilyId<F>>;

    /// Recompute a reused channel slot in the family that fired and draw a fresh NRM clock.
    fn reinitialize(&mut self, local_channel: usize);

    /// Recompute a reused channel slot in a named family and draw a fresh NRM clock.
    fn reinitialize_family<I>(&mut self, family: I, local_channel: usize)
    where
        I: Into<FamilyId<F>>;
}

#[doc(hidden)]
pub trait FamilyUpdateBuffer {
    fn clear(&mut self);

    fn push(&mut self, update: FamilyChannelUpdate);

    fn pop(&mut self) -> Option<FamilyChannelUpdate>;
}

/// Reusable heap-backed dependency-update buffer.
#[doc(hidden)]
#[derive(Debug, Clone, Default)]
pub struct FamilyChannelUpdates {
    updates: Vec<FamilyChannelUpdate>,
}

impl FamilyUpdateBuffer for FamilyChannelUpdates {
    #[inline(always)]
    fn clear(&mut self) {
        self.updates.clear();
    }

    #[inline(always)]
    fn push(&mut self, update: FamilyChannelUpdate) {
        self.updates.push(update);
    }

    #[inline(always)]
    fn pop(&mut self) -> Option<FamilyChannelUpdate> {
        self.updates.pop()
    }
}

/// Dependency-update buffer that stores the first `N` entries inline and reuses heap spill space.
#[doc(hidden)]
#[derive(Debug, Clone)]
pub struct InlineFamilyChannelUpdates<const N: usize> {
    inline: [FamilyChannelUpdate; N],
    inline_len: usize,
    overflow: Vec<FamilyChannelUpdate>,
}

impl<const N: usize> Default for InlineFamilyChannelUpdates<N> {
    fn default() -> Self {
        Self {
            inline: [FamilyChannelUpdate {
                family: 0,
                local_channel: 0,
                kind: FamilyUpdateKind::Recompute,
            }; N],
            inline_len: 0,
            overflow: Vec::new(),
        }
    }
}

impl<const N: usize> FamilyUpdateBuffer for InlineFamilyChannelUpdates<N> {
    #[inline(always)]
    fn clear(&mut self) {
        self.inline_len = 0;
        self.overflow.clear();
    }

    #[inline(always)]
    fn push(&mut self, update: FamilyChannelUpdate) {
        if self.inline_len < N {
            self.inline[self.inline_len] = update;
            self.inline_len += 1;
        } else {
            self.overflow.push(update);
        }
    }

    #[inline(always)]
    fn pop(&mut self) -> Option<FamilyChannelUpdate> {
        if let Some(update) = self.overflow.pop() {
            return Some(update);
        }
        if self.inline_len == 0 {
            return None;
        }
        self.inline_len -= 1;
        Some(self.inline[self.inline_len])
    }
}

pub(crate) struct FamilyLocalUpdateWriter<'a, S, F> {
    family: usize,
    sink: &'a mut S,
    family_set: PhantomData<fn() -> F>,
}

impl<'a, S, F> FamilyLocalUpdateWriter<'a, S, F>
where
    S: FamilyUpdateBuffer,
{
    pub(crate) fn new(family: FamilyId<F>, sink: &'a mut S) -> Self {
        Self {
            family: family.index(),
            sink,
            family_set: PhantomData,
        }
    }

    #[inline(always)]
    fn push(&mut self, family: usize, local_channel: usize, kind: FamilyUpdateKind) {
        self.sink.push(FamilyChannelUpdate {
            family,
            local_channel,
            kind,
        });
    }
}

impl<S, F> ChannelRecomputeSink<F> for FamilyLocalUpdateWriter<'_, S, F>
where
    S: FamilyUpdateBuffer,
{
    #[inline(always)]
    fn recompute(&mut self, local_channel: usize) {
        self.push(self.family, local_channel, FamilyUpdateKind::Recompute);
    }

    #[inline(always)]
    fn recompute_family<I>(&mut self, family: I, local_channel: usize)
    where
        I: Into<FamilyId<F>>,
    {
        self.push(
            family.into().index(),
            local_channel,
            FamilyUpdateKind::Recompute,
        );
    }

    #[inline(always)]
    fn reinitialize(&mut self, local_channel: usize) {
        self.push(self.family, local_channel, FamilyUpdateKind::Reinitialize);
    }

    #[inline(always)]
    fn reinitialize_family<I>(&mut self, family: I, local_channel: usize)
    where
        I: Into<FamilyId<F>>,
    {
        self.push(
            family.into().index(),
            local_channel,
            FamilyUpdateKind::Reinitialize,
        );
    }
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;

    struct Families;

    #[test]
    fn writer_records_current_cross_family_and_reinitialized_channels() {
        let mut updates = FamilyChannelUpdates::default();
        // SAFETY: this unit test's dummy family set treats these indices as configured families.
        let current = unsafe { FamilyId::<Families>::__from_index_unchecked(1) };
        // SAFETY: this unit test's dummy family set treats these indices as configured families.
        let other = unsafe { FamilyId::<Families>::__from_index_unchecked(2) };
        {
            let mut writer = FamilyLocalUpdateWriter::new(current, &mut updates);
            writer.recompute(3);
            writer.recompute_family(other, 4);
            writer.reinitialize(5);
        }

        assert_eq!(
            updates.pop(),
            Some(FamilyChannelUpdate {
                family: 1,
                local_channel: 5,
                kind: FamilyUpdateKind::Reinitialize,
            })
        );
        assert_eq!(
            updates.pop(),
            Some(FamilyChannelUpdate {
                family: 2,
                local_channel: 4,
                kind: FamilyUpdateKind::Recompute,
            })
        );
        assert_eq!(
            updates.pop(),
            Some(FamilyChannelUpdate {
                family: 1,
                local_channel: 3,
                kind: FamilyUpdateKind::Recompute,
            })
        );
    }

    #[test]
    fn inline_buffer_spills_without_panicking_and_reuses_capacity() {
        let mut updates = InlineFamilyChannelUpdates::<1>::default();
        // SAFETY: this unit test's dummy family set treats index zero as configured.
        let current = unsafe { FamilyId::<Families>::__from_index_unchecked(0) };
        {
            let mut writer = FamilyLocalUpdateWriter::new(current, &mut updates);
            writer.recompute(0);
            writer.recompute(1);
        }

        assert_eq!(updates.pop().map(|update| update.local_channel), Some(1));
        assert_eq!(updates.pop().map(|update| update.local_channel), Some(0));
        assert_eq!(updates.pop(), None);

        updates.clear();
        let mut writer = FamilyLocalUpdateWriter::new(current, &mut updates);
        writer.recompute(2);
        assert_eq!(updates.pop().map(|update| update.local_channel), Some(2));
    }
}
